def test_browser_denial_recovery_and_user_switch(browser, live_server):
    page = browser.new_page()
    page.goto(f"{live_server}/sign-in")
    page.get_by_label("Email").fill("outsider@example.test")
    page.get_by_label("Password").fill("correct-password")
    page.get_by_role("button", name="Sign in").click()
    page.goto(f"{live_server}/services/demo")
    assert page.get_by_role("heading", name="Access denied").is_visible()
    page.get_by_role("link", name="Return to service list").click()
    page.get_by_role("button", name="Sign out").click()
    page.get_by_label("Email").fill("member@example.test")
    page.get_by_label("Password").fill("correct-password")
    page.get_by_role("button", name="Sign in").click()
    page.goto(f"{live_server}/services/demo")
    assert page.get_by_text("Protected service reached.").is_visible()
    page.close()
